Repository reaganmcf/lightmon, pull requests merged in 2021-04, with the labels that each got.

#5 New CI workflow
  .github/workflows/ci.yml
  README.md
  src/cli.rs
  src/exec.rs
  src/main.rs
  src/watcher.rs
  tests/cli.rs
Labels: enhancement

#8 Automatic Language Detection
  src/cli.rs
  tests/cli.rs
Labels: enhancement

#11 Remove no arg test
  src/cli.rs
  tests/cli.rs
Labels: bug

#14 💄/ 🩹 :stderr prints red and stdout always prints
  Cargo.lock
  Cargo.toml
  README.md
  src/cli.rs
  src/exec.rs
Labels: bug

#18 ✨ `cli::build_node_config()` resolves exec_commands using package.json
  Cargo.lock
  Cargo.toml
  src/cli.rs
Labels: bug, enhancement

#17 ✨ Enables user restart by entering rs in stdin (#12)
  src/exec.rs
  src/main.rs
Labels: enhancement

#23 📝 Rewrote readme examples and inline doc strings
  README.md
  src/cli.rs
  src/exec.rs
  src/main.rs
  src/watcher.rs
Labels: documentation

#24 Cargo subcommands
  .gitignore
  README.md
  src/cli.rs
  src/cli.yaml
  tests/example_projects/rust_invalid/Cargo.toml
  tests/lightmon.rs
  tests/node.rs
  tests/rust.rs
  tests/shell.rs
  tests/utils.rs
Labels: enhancement, help wanted
